#!/usr/bin/env bash
# script to get info dns


func () {
    if [ -z "$1" ]
    then
    	exit
    fi
	domain=$1
	if [ -z "$2" ]
	then
		subdomainList=('www' 'lb-01' 'web-01' 'web-02')
		for ((i=0; i<4; i++))
		do
			path="${subdomainList[i]}".$domain
			ip=$(dig "$path" | grep -A1 'ANSWER SECTION:' | awk "/${subdomainList[i]}.megablog.tech./ {print \$5}")
			record_type=$(dig "$path" | grep -A1 'ANSWER SECTION:' | awk "/${subdomainList[i]}.megablog.tech./ {print \$4}")
			echo "The subdomain ${subdomainList[i]} is a $record_type record and points to $ip"
		done
	else
		subdomain=$2
		path=$subdomain.$domain
		pattern=$subdomain."megablog.tech."
		ip=$(dig "$path" | grep -A1 'ANSWER SECTION:' | awk "/$pattern/ {print \$5}")
		record_type=$(dig "$path" | grep -A1 'ANSWER SECTION:' | awk "/$pattern/ {print \$4}")
		echo "The subdomain $subdomain is a $record_type record and points to $ip"
	fi
}
func "$@"
