#!/usr/bin/env bash
# script that transfers a file from our client to a server
if [ "$#" -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	file_path=$1
	ip=$2
	usr=$3
	key=$4
	scp -o "StrictHostKeyChecking=no" -i "$key" "$file_path" "$usr"@"$ip":~/
fi
