#!/usr/bin/env bash
# script to install HAproxy
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get install -y haproxy=2.8.\*
sudo sed -i '$a frontend http\n\t\
        bind *:80\n\t\
        mode http\n\n\t\
        default_backend web-backend\n\n' /etc/haproxy/haproxy.cfg
sudo sed -i '$a backend web-backend\n\t\
        balance roundrobin\n\t\
        server 386537-web-01 52.23.178.138:80 check\n\t\
        server 386537-web-02 100.25.29.150:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
