#!/usr/bin/env bash
# script to create a back-up for the DB

today=$(date +%d-%m-%y)
sudo mysqldump -uroot -p"$1" --all-databases > backup.sql
file_name="$today.tar.gz"
tar -czvf "$file_name" backup.sql
