#!/usr/bin/env bash
# script stops
# shellcheck disable=SC2009
touch /var/run/myscript.pid
trap 'echo "I hate the kill command";rm /var/run/myscript.pid; exit' SIGTERM SIGQUIT 
trap 'echo "Y U no love me?!"' SIGINT
while true
do
	echo "To infinity and beyond"
	sleep 3
done
