#!/usr/bin/env bash
# script displays To infinity and beyond indefinitely
# shellcheck disable=SC2009

trap 'echo "I am invincible!!!"' SIGTERM
trap - SIGINT
while true
do
	echo "To infinity and beyond"
	sleep 2
done
