#!/usr/bin/env bash
# use the if, elif and else statements

i=0
while [ $i -le 9 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
