#!/usr/bin/env bash
#script to adress resolves to defferent ip

cp /etc/hosts ~/hosts.new
sed -i -e '$a8.8.8.8	facebook.com' ~/hosts.new
sed -i '/127.0.0.1	localhost/c\127.0.0.2	localhost' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
