#!/usr/bin/env bash
#script to change user and port
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default;
sudo sed -i "s/www-data/nginx/g" /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
